### ISSUE TITLE
Ideas Proyectos - Subvenciones curso 2018-2019

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/FENIX#1]
Copiando (literalmente) a nuestros compañeros de Printer One, también abro la veda para proponer proyectos a la uni.

Posible haga falta una issue en actas para ponernos todos de acuerdo.

Plagiado de https://github.com/asrob-uc3m/impresoras-asrob/issues/97

**Comment by GioSunrider** [comment]
Yo propongo una subvencion para la compra de materiales para el circuito ademas del uso del makerspace. Y dejo a @JavierIH que decida si la pedimos para un Taller de Papa Noeles.

**Comment by David-Estevez** [comment]
> Posible haga falta una issue en actas para ponernos todos de acuerdo.

Traducción: luchar a muerte en una arena para ganar el derecho a pedir subvenciones :laughing:

**Comment by alejanpa17** [comment]
Para hacer el taller de los Papa Noeles tenemos material básico? Como por ejemplo soldadores, estaño, cable, tornillos...

**Comment by GioSunrider** [comment]
Dudo de los tornillos, al ser muy pequeños, no estoy seguro. El resto esta todo el material disponible.
